package rules.CultureMaster;

import java.lang.string.*; 
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.time.LocalDateTime;

import org.apache.commons.lang3.StringUtils;

import com.mindsmiths.emailAdapter.EmailAdapterAPI;
import com.mindsmiths.emailAdapter.SendEmailPayload;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.sdk.utils.templating.Templating;
import com.mindsmiths.mitems.Mitems;

import agents.CultureMaster;

rule "Mail sending"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: CultureMaster(
            lastEmailSentTime before[5s] ts
            //pinged == false
        )
    then
        modify(agent) {
            setLastEmailSentTime(new Date())
            //setPinged(true)
        };
        Log.info("5 seconds have passed...");

        String subject = Mitems.getText("onboarding.welcome-email.subject");
        String description = Mitems.getText("onboarding.welcome-email.description");
        String htmlTemplate = String.join("", Files.readAllLines(Paths.get("EmailTemplate.html"), StandardCharsets.UTF_8));

        String htmlBody = Templating.recursiveRender(htmlTemplate, Map.of(
            "description", description,
            "callToAction", "Let's go",
            "armoryUrl", "http://8000.workspace-ms-86851026.sandbox.mindsmiths.io/"
        ));

        SendEmailPayload e = new SendEmailPayload();
        e.setRecipients(List.of("tomislav.matic01@gmail.com"));
        e.setSubject(subject);
        e.setHtmlText(htmlBody);
        EmailAdapterAPI.newEmail(e);
end

rule "Updating time"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: CultureMaster()
    then
        modify(agent) {
            setTimeNow(LocalDateTime.now())
        }    
end

rule "Working hours"
    when
        agent: CultureMaster(timeNow.getDayOfWeek() != "SATURDAY", timeNow.getDayOfWeek() != "SUNDAY",
                             timeNow.getHour() > 8 , timeNow.getHour() < 17)
    then
        modify(agent) {
            setDecentTime(true)
        }
end