package rules.cultureMaster;

import com.mindsmiths.ruleEngine.model.Heartbeat
import agents.CultureMaster
import models.CronTime


rule "Pairing interval"
    salience 500
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: CultureMaster(pairingInterval != CronTime.PAIRING_INTERVAL.isSatisfied(ts), pairingInterval : pairingInterval)
    then
        modify(agent){
            setPairingInterval(!pairingInterval)
        }
end
