package rules.CultureMaster;

import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Initialize;
import com.mindsmiths.pairingalgorithm.Result;

import agents.CultureMaster;

import java.util.Date;


rule "First contact"
    salience 100
    when
        initialize: Initialize() from entry-point "agent-created"
        agent: CultureMaster()
    then
        Log.info("Created new CultureMaster agent.");
end

rule "CultureMaster's Heartbeat"
    when
        Heartbeat() from entry-point "signals"
        agent: CultureMaster()
    then
        Log.info("generating pairs");
        agent.generatePairs();
end

rule "Send Generate Pairs Response"
    when
        finalPairs: Result() from entry-point "signals"
        agent: CultureMaster()
    then
        modify(agent) {addFinalPairs(finalPairs.getResult())};
        Log.info("---------------------rezultati---------------------");
        Log.info(finalPairs.getResult());
        delete(finalPairs);
end

rule "Add New Ava ID"
    when
        newId: from entry-point "new-agent-id"
        agent: CultureMaster()
    then
        modify(agent) {addNewID()}
        delete(newId)
end

rule "Request Availability Data"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: CultureMaster(
            lastGeneratePairsTime before[10s] ts
        )
        newId
    then
        modify(agent) {
            lastGeneratePairsTime(new Date())
        };
        Log.info("10 seconds have passed...");
        // TODO
        // trazi podatke od ava
        for (String id : agent.avaIDs) {
            agent.send(id, initialize, "dodaj nesto");
        }
        // triggeraj rule za generiranje novih parova
end

