package rules.cultureMaster;

import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Initialize;
import com.mindsmiths.pairingalgorithm.Matches;
import com.mindsmiths.pairingalgorithm.LunchCompatibilities;

import signals.EmployeeConnectionStrengthsSignal;
import signals.EmployeeAvailabilitySignal;

import agents.CultureMaster;
import models.CmLunchCycleStage;

rule "Store Employee availability"
    when
        signal: EmployeeAvailabilitySignal(employeeAvailability: employeeAvailability) from entry-point "signals"
        agent: CultureMaster(lunchCycleStage == CmLunchCycleStage.COLLECT_AVA_AVAILABILITIES)
    then
        modify(agent) {addEmployeeAvailability(employeeAvailability)};
        delete(signal);
end

rule "Store employee connection strengths"
    when
        signal: EmployeeConnectionStrengthsSignal(connectionStrengths: connectionStrengths) from entry-point "signals"
        agent: CultureMaster()
    then
        
        modify(agent){getEmployeeConnectionStrengths().put(signal.getFrom(), connectionStrengths)};
        delete(signal);
end

rule "Store generated matches"
    when
        generatedMatches: Matches(allMatches: allMatches) from entry-point "signals"
        agent: CultureMaster(lunchCycleStage == CmLunchCycleStage.COLLECT_GENERATED_MATCHES)
    then
        modify(agent) {
            sendMatches(allMatches),
            setLunchCycleStage(CmLunchCycleStage.FINISHED),
            clearEmployeeAvailabilities()
        };
        delete(generatedMatches);
end

rule "Reset lunch cycle"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        agent: CultureMaster(lunchCycleStage != CmLunchCycleStage.COLLECT_AVA_AVAILABILITIES)
        eval(evaluateCronExpression("* * 18-19 ? * FRI *", ts, "Europe/Zagreb"))
    then
        modify(agent) {setLunchCycleStage(CmLunchCycleStage.COLLECT_AVA_AVAILABILITIES)};
end 

rule "Store lunch compatibilities"
    when
        signal: LunchCompatibilities() from entry-point "signals"
        agent: CultureMaster()
    then
        modify(agent) {setLunchCompatibilities(signal)};
end