# Generated by Django 3.2.15 on 2022-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('first_employee', models.CharField(max_length=200)),
                ('second_employee', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
