# Generated by Django 3.2.15 on 2022-09-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='day',
            new_name='day_of_week',
        ),
    ]
