package rules.Ava;

import java.lang.string.*; 
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.time.LocalDateTime;

import org.apache.commons.lang3.StringUtils;

import com.mindsmiths.emailAdapter.EmailAdapterAPI;
import com.mindsmiths.emailAdapter.SendEmailPayload;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.sdk.utils.templating.Templating;
import com.mindsmiths.mitems.Mitems;
import static com.mindsmiths.ruleEngine.util.DateUtil.evaluateCronExpression;

import agents.CultureMaster;
import agents.Ava;


rule "Working hours"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        eval(evaluateCronExpression("* * 8-17 ? * MON-FRI *", ts, "Europe/Zagreb"))
        agent: Ava()
    then
        modify(agent) {
            setWorkingHours(true)
        }
end

rule "Non working hours"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        eval(!evaluateCronExpression("* * 8-17 ? * MON-FRI *", ts, "Europe/Zagreb"))
        agent: Ava()
    then
        modify(agent) {
            setWorkingHours(false)
        }
end

rule "First weekly mail sending"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        //eval(evaluateCronExpression("* * 8-17 ? * FRI *", ts, "Europe/Zagreb"))
        agent: Ava()
    then
        modify(agent) {};

        Log.info("I live!");

        String subject = Mitems.getText("onboarding.welcome-email.subject");
        String description = Mitems.getText("onboarding.welcome-email.description");
        String htmlTemplate = String.join("", Files.readAllLines(Paths.get("EmailTemplate.html"), StandardCharsets.UTF_8));

        String htmlBody = Templating.recursiveRender(htmlTemplate, Map.of(
            "description", description,
            "callToAction", "Let's go",
            "armoryUrl", "http://8000.workspace-ms-86851026.sandbox.mindsmiths.io/"
        ));

        SendEmailPayload e = new SendEmailPayload();
        e.setRecipients(List.of("filipbacic08@gmail.com"));
        e.setSubject(subject);
        e.setHtmlText(htmlBody);
        EmailAdapterAPI.newEmail(e);
end

