package rules.Ava;
import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;

import com.mindsmiths.armory.events.UserConnectedEvent;
import com.mindsmiths.armory.events.SubmitEvent;
import agents.Ava;

rule "Hello world"
   when
       signal: UserConnectedEvent() from entry-point "signals"
       agent: Ava(introScreenShowed == false)
   then
       agent.showIntroScreen();
       modify(agent) {setIntroScreenShowed(true)};
       delete(signal);
end