package rules.ava;

import com.mindsmiths.employeeManager.ManualTriggerEvent;

import agents.Ava;

import models.OnboardingStage
import models.OnboardingTemplates;
import models.LunchCycleData;
import models.MonthlyCoreData
import com.mindsmiths.employeeManager.employees.Employee

rule "Trigger onboarding"
    when
        signal: ManualTriggerEvent(triggerType == "onboarding") from entry-point "signals"
        agent: Ava(onboarded == false, armory: getConnection("armory"), email: getConnection("email"))
        employee: Employee(active == true)
    then
        agent.sendEmail(OnboardingTemplates.welcomeEmail(employee,  armory, email));
        modify(agent) {setOnboardingStage(OnboardingStage.WELCOME_EMAIL_SENT)};
        delete(signal);
end

