package rules.Ava;

import static com.mindsmiths.ruleEngine.util.DateUtil.evaluateCronExpression;
import com.mindsmiths.ruleEngine.model.Heartbeat;

import agents.Ava;


rule "Set working hours"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        eval(evaluateCronExpression("* * 8-17 ? * MON,TUE,WED,TUE,FRI *", ts, "Europe/Zagreb"))
        agent: Ava(workingHours != true)
    then
        modify(agent) {
            setWorkingHours(true)
        }
end

rule "Set non working hours"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        eval(!evaluateCronExpression("* * 8-17 ? * MON,TUE,WED,TUE,FRI *", ts, "Europe/Zagreb"))
        agent: Ava(workingHours != false)
    then
        modify(agent) {
            setWorkingHours(false)
        }
end