package rules.Ava;

import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Initialize;
import signals.RequestAvailableDays;
import signals.SendAvailableDays;
import signals.NewAvaRegistered;
import signals.MatchInfoSignal;
import agents.Ava;
import agents.CultureMaster;

rule "First contact"
    salience 100
    when
        initialize: Initialize() from entry-point "agent-created"
        agent: Ava()
    then
        agent.send(CultureMaster.ID, new NewAvaRegistered(agent.getId()));
        Log.info("Sent my id to CM " + agent.getId());
        delete(initialize);
end

rule "Send Available Days"
    when
        signal: RequestAvailableDays() from entry-point "signals"
        agent: Ava()
    then
        modify(agent) {updateAvaAvailability()};
        agent.send(CultureMaster.ID, new SendAvailableDays(agent.getAvaAvailability()));
        delete(signal)
end

rule "Accept Match Info"
    when
        signal: MatchInfoSignal() from entry-point "signals"
        agent: Ava()
    then
        modify(agent) {setMatchName(signal.getMatchName()), setMatchDay(signal.getMatchDay())};
        Log.info("I'm " + agent.getId() + " and my match is " + agent.getMatchName() + " on " + agent.getMatchDay());
        delete(signal);
end

