package rules.Ava;

import com.mindsmiths.sdk.utils.templating.*;
import com.mindsmiths.ruleEngine.util.Agents;
import com.mindsmiths.ruleEngine.model.Initialize;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.employeeManager.employees.Employee;

import static com.mindsmiths.ruleEngine.util.DateUtil.evaluateCronExpression;

import agents.Ava;
import agents.CultureMaster;

import signals.NumOfSilosSignal;
import signals.SilosInfoSignal;

import models.EmployeeProfile;

// this never triggers?
rule "Send stats email"
    when
        Heartbeat(ts: timestamp) from entry-point "signals"
        eval(evaluateCronExpression("* * * ? * 2#1 *", ts, "Europe/Zagreb"))
        agent: Ava(
            statsEmailLastSentAt == null || statsEmailLastSentAt before[1d] ts,
            workingHours == true
        )
        employee: EmployeeProfile()
    then
        modify(agent) {
            setStatsEmailLastSentAt(ts)
        };
        agent.send(CultureMaster.ID, new NumOfSilosSignal(agent.getId()));
        agent.sendStatisticsEmail(employee);
end

rule "Store num of silos"
    when
        signal: SilosInfoSignal() from entry-point "signals"
        agent: Ava()
    then
        modify(agent) {setNumOfSilos(signal.getNumOfSilos())};
        delete(signal);
end


rule "Connect stats screens with email"
   when
        signal: UserConnectedEvent(getParamAsString("trigger") == "show-stats") from entry-point "signals"
        agent: Ava()
   then
        agent.showEmployeeNumberScreen();
        delete(signal);
end