# Generated by Django 3.2.15 on 2022-12-23 11:03

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(db_index=True, default=employees.models.Employee.create_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
