# Generated by Django 3.2.15 on 2022-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20220908_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
