package rules.Panic;

import com.mindsmiths.ruleEngine.util.Agents;

rule "First contact"
    salience 100
    when
        initialize: Initialize() from entry-point "agent-created"
        agent: Ava()
    then
        agent.sendMessage("Okay, turning my engines on. Let's start!");
        agent.send("AVA", initialize, "new-agent");
        delete(message);
end

rule "Get available days"
    when
        
    then