package rules.Smith;
import com.mindsmiths.mitems.Mitems;
import com.mindsmiths.ruleEngine.model.Heartbeat;
import com.mindsmiths.ruleEngine.util.Log;
import com.mindsmiths.ruleEngine.util.Agents;


rule "Smith's Heartbeat"
    when
        Heartbeat() from entry-point "signals"
    then
        Log.info("Smith's heartbeat - num agents: " + Agents.getCount());
        //Log.info(Mitems.getText("test.capa.element")); - test
end