apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: new-ava-dev
  namespace: new-ava-main
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods", "pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/portforward", "pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["", "batch"]
  resources: ["pods", "jobs"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: new-ava-dev
  namespace: new-ava-main
roleRef:
  kind: Role
  name: new-ava-dev
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: domagoj.blazanin@mindsmiths.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: lora.benjak@mindsmiths.com
