package models;

public enum OnboardingStage {
    AVA_CREATED,
    WELCOME_EMAIL_SENT,
    FAMILIARITY_QUIZ,
    FAMILIARITY_STORED,
    PERSONAL_QUIZ_INTRO,
    PERSONAL_QUIZ,
    WAIT_FOR_PERSONAL_ANSWER,
    FINISHED;
}